### ISSUE TITLE
Scaling doesn't work right

### ISSUE THREAD

**Issue by Evanineo** [zowepsilon/Functional#1]
If you scale an object using the function thingy, the scale doesn't persist. Let's say I have a spike and I use the function thingy to scale it vertically by 7.352341 or something (just anything at all), there's an issue where it resets its scale when you do pretty much anything, like copy and pasting it, opening up the level in the editor or to play it, and a lot of other stuff.

**Comment by zowepsilon** [comment]
i already have fixed this issue, the version is just not on the geode index right now. you can download the latest version in the actions tab or wait a few days for the new version to be published on the index.
edit: the new version is out on the index
